title: Curriculum Configuration
curator: Sunny Aggarwal
authors: # author vs authors distinction??? string vs array? two different things necessarily? or can adding an s make it necessarily a parent of individual components? I think ruby kinda works like that.
source: https://www.example.com
type: # item type (like paper, section, podcast, etc.) (probably use quantity neutral terminology like podcast, film.. or maybe its better to have a distinguished variable for multiple of film == films)
      # the reason I like type is its like `type: paper` is the same as `- paper:`.. i'm imagining each of these files I create as potentially modules.

description: >
    You got all the space

    and as many lines as you need for description.

items:
  - paper:
      title:          # of resource whether it's 'paper' 'book', etc.
      link:           # basically every item has a link
      description:    # Required (unless maybe you use isbn or have a series of items that contain all your metadata)
  - section:          # Of curriculum
      title:          # of section
      items:          # within section
        - article:
            title:
            link:
        - book:
            title:
            isbn:
            link: 
  - article:
      title: 
      link:
      description:
      items:
          - video:
              title: Video belonging to the article or contrawise
              link: 
              description:
              optional: true 
  - website:
      title: 
      link:
  - text:
      description: 
  - book:
      title: 
      author:
      link: 
      description: >
          indented to r
  - podcast:
      title:
      link:
      items:
        - episode:
          title:
          description:

